"use client"
import 'leaflet/dist/leaflet.css';
import HeaderNavBar from '@/components/HeaderNavBar'
import Provider from './Provider'
import './globals.css'
import { Raleway } from 'next/font/google'
import { useEffect, useState,useRef } from 'react'
import { UserLocationContext } from '../context/UserlocationContext'
import { SelectedBusinessContext } from '@/context/SelectedBusinessContext';
import { RadiusContext } from '@/context/RadiusContext';
import { BusinessProvider } from '@/context/SearchBusinessContext';


const raleway = Raleway({ subsets: ['latin'] })

const metadata = {
  title: 'Lipsa Das',
  description: 'Generated by Lipsa Das',
}

export default function RootLayout({ children }) {
 
  const [userLocation,setUserLocation]=useState([]);
  const [selectedBusiness,setSelectedBusiness]=useState([]);
  const [radius, setRadius] = useState(5); // default radius]);
  const radiusRef = useRef(radius);
  
  useEffect(()=>{
    getUserLocation();
  },[])
  const getUserLocation=()=>{
    navigator.geolocation.getCurrentPosition(function(pos){
      console.log(pos)
      setUserLocation({
        lat:pos.coords.latitude,
        lng:pos.coords.longitude
      })
    })
  }

  // Keep the ref in sync with the state
useEffect(() => {
  radiusRef.current = radius;
}, [radius]);
 
  return (
    <html lang="en">
      <body className={raleway.className} >
        <Provider>
          <BusinessProvider>
          <SelectedBusinessContext.Provider value={{selectedBusiness,setSelectedBusiness}}>
          <UserLocationContext.Provider value={{userLocation,setUserLocation}}>
          <RadiusContext.Provider value={{ radius, setRadius }}>
          <HeaderNavBar />
             {children}
          </RadiusContext.Provider>
          </UserLocationContext.Provider>
          </SelectedBusinessContext.Provider>
          </BusinessProvider>
     
        </Provider>
        </body>
    </html>
  )
}